# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='dash_board.DashBoard'),
        ),
    ]
