# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pd_df_cache', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrameColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='dataframecache',
            name='df_loc',
            field=models.FileField(blank=True, upload_to='dataframes/'),
        ),
        migrations.AddField(
            model_name='dataframecache',
            name='name',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dataframecolumn',
            name='df_cache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd_df_cache.DataFrameCache'),
        ),
    ]
