# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dash_board', '0001_initial'),
        ('p3app', '0003_auto_20161128_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('xlabel', models.TextField(blank=True, null=True)),
                ('ylabel', models.TextField(blank=True, null=True)),
                ('cell', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash_board.Cell')),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.TextField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p3app.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('cell', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash_board.Cell')),
            ],
        ),
    ]
