# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='cell',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='dash_board.Cell'),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='cell',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textdata', to='dash_board.Cell'),
        ),
    ]
