# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20161130_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('pie', 'pie'), ('donut', 'donut'), ('hist', 'hist'), ('bar', 'bar'), ('scatter', 'scatter'), ('time', 'time')], default='pie', max_length=20),
            preserve_default=False,
        ),
    ]
