# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_chart_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='cell',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='dash_board.Cell'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charts.Chart'),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='cell',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textdata', to='dash_board.Cell'),
        ),
    ]
