# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_auto_20161213_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('pie', 'pie'), ('donut', 'donut'), ('hist', 'hist'), ('bar', 'bar'), ('stackedbar', 'stackedbar'), ('scatter', 'scatter'), ('time', 'time')], max_length=20),
        ),
    ]
