# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pd_df_cache', '0002_auto_20161111_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('is_csv', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_cache', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pd_df_cache.DataFrameCache')),
            ],
        ),
    ]
