# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p3app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p3app.DataSet')),
            ],
        ),
    ]
